### ISSUE TITLE
Recommend Game Title

### ISSUE THREAD

**Issue by anemperor** [AfterHoursGameDev/StraightToAle#26]
Have some game title ideas ready for Monday Discord meeting

**Comment by abiglari86** [comment]
Here are some ideas:

**Stale Wars** (Straight To ALE wars)
**Alien Demons Attack!** (a play on Mars Attacks!)
**Demon Beer Game** (so plain, it sticks out)
**Monkey Beer Mania** (I just thought this kind of sounded fun)
**Fuzzy Interceptor** (get it? the monkey's fuzzy and when you drink beer you get fuzzy...)
**Intercept This** (a play on the movie Analyze This)
**Monkey Beer Gun** (if this doesn't make you say "what?" please check your pulse)
**Monkey See, Monkey Shoot** (play on monkey see, monkey do)
**DIP-666: Demon Intercepting Primate** (mimicks the type of names assigned to interecptor aircraft)
**Beer Blaster** (short, sweet, and to the point... an alternative would be Demonic Beer Blaster or Monkey Beer Blaster)
**Primate: The Last Beerblaster** (a play on the movie Avatar: The Last Airbender)
**See no Evil, Beer no Evil** (a play on the movie See No Evil, Hear No Evil)
**Beer Kong** (a combination of King Kong and Beer Pong)

**Comment by FlyingFatman** [comment]
Miss-Ale Command/Defense
Chimp Command
Space Chimp
Trouble Brewing
Hopping Mad
Brew-tiful Disaster
The Devil`s Brew (the devil`s due)
The Hair Raising Adventures of Monkeynaut in Spaaaaaaaaaace!
